language: node_js

node_js:
  - "18"

cache: yarn

# branches:
#   only:
#     - master

jobs:
  include:
    - stage: install
      name: "Install Dependencies"
      script:
        # This is required by Node 18
        - sudo apt install libc6
        - yarn install --immutable --immutable-cache --check-cache
    - stage: test
      name: "Unit Tests + Coverage"
      script:
        - yarn test:coverage
        - echo "Report Coverage..."
        - yarn codecov
    - stage: publish
      name: "Build and publish to NPM"
      script: skip
      before_deploy:
        - echo "Building..."
        - yarn build:ci
        - echo "Deploying..."
      deploy:
        provider: script
        skip_cleanup: true # will be deprecated in dpl2
        script: yarn semantic-release
        on:
          branch: master

stages:
  - install
  - test
  - publish
